import LocalizedStrings from 'react-localization'

const Localization = new LocalizedStrings({
 es: {
   // footer
   about: 'About',
   contact: 'Contacto',
   usage: 'Términos y Condiciones',
   privacy: 'Política de Privacidad',
   logout: 'Salir',
   // header
   login: 'Entrar',
   time: 'Agregar Tiempo',
   //landing
   sign: 'Entrar Con Instagram',
   mainheader: 'Seguidores reales en muy poco tiempo',
   subheader: 'Sólo tienes que iniciar sesión y personalizar tu experiencia. Empezarás a tener seguidores reales en muy poco tiempo, listos para interactuar contigo',
   ease: 'Fácil de usar',
   everyone: 'Para todos',
   organic: 'Completamente orgánica',
   ease_exp: 'No pierdas tiempo con configuraciones complicadas. Comenzar toma sólo un par de clics, sin necesidad de descargar nada',
   everyone_exp: 'Para creadores de contenido, emprendedores, músicos, cualquier persona. Lo importante es que quieras crecer',
   organic_exp: 'Te garantizamos crecer con personas reales. Sin bots ni cuentas falsas',
   header: 'La plataforma más poderosa y fácil de usar para crecer tu cuenta de Instagram',
   reach: 'Crece tu cuenta',
   reach_exp: 'Muchas personas por ahí están literalmente comprando seguidores. Sin embargo, estos son sólo usuarios falsos que no interactúan con ellos de ninguna manera. OWA Influencers te garantiza obtener seguidores reales de Instagram, los cuáles estarán genuinamente enamorados de tu perfil y de tu contenido.',
   reach_exp2: 'Déjanos administrar tu cuenta. Sólo necesitas configurar algunas opciones y nosotros nos encargaremos del resto, incluso cuando no estés conectado.',
   audience: 'Encuentra a tu audiencia',
   audience_exp: 'No tiene caso que incrementar tus seguidores si te dejarán de seguir al siguiente día. Para comprometer a los usuarios contigo, es necesario que encuentres a las personas que les encanta tu contenido',
   content: 'Contenido',
   content_exp: 'A través de hashtags, llega a usuarios con ciertos intereses específicos',
   location: 'Ubicación',
   location_exp: 'Encuentra e interactúa con usuarios en base a su ubicación. Negocios locales, áreas específicas, ciudades e incluso estados enteros. Localiza tu audiencia',
   exceptions: 'Excepciones',
   exceptions_exp: 'Deja fuera hashtags, usuarios e incluso palabras no deseadas. Interactúa sólo con cuentas que sean relevantes para ti',
   users: 'Special Follow',
   users_exp: 'Contáctanos y atrae usuarios específicos con los que deseas interactuar.',
   attention: 'Tú eres el centro de atención',
   expose: 'Deja que las personas te vean y te sigan',
   hall: 'Salón de la Fama',
   hall_exp: 'Haz que tu cuenta sea el centro de atención para otros usuarios de OWA.',
   hall_exp2: 'Así obtendrás seguidores de manera más rápida y directa',
   package_time: 'Sólo el tiempo necesario',
   time_exp: 'OWA Influencers es sin duda la mejor plataforma para hacer crecer tu cuenta de Instagram a un precio muy económico.',
   time_exp2: 'Mira algunos de los paquetes que tenemos para ti',
   day: 'día',
   day_s: 'días',
   per_day: 'por día',
   packages: 'Con todos nuestros paquetes creces tu cuenta y obtienes interacción con usuarios reales',
   wave: '¿Estás listo para recibir una oleada de seguidores?',
   enter: 'Entra ahora y comienza a crecer tu cuenta de Instagram',
   //signin
   signin: 'Iniciar Sesión',
   ig_user: 'Usuario de Instagram',
   ig_password: 'Contraseña de Instagram',
   verify_account: 'Debes verificar tu cuenta. Por favor inicia sesión en ',
   ig: 'Instagram',
   verify_account2: ' y verifica que fuiste tú',
   continue: 'He verificado, Continuar',
   accept: 'Al iniciar sesión, aceptas nuestros términos y condiciones',
   //time card
   remaining: 'Tiempo Restante',
   days: 'Días',
   //hall of fame
   fame: 'Salón de la Fama',
   following_hall: 'Siguiendo',
   follow: 'Seguir',
   // switches
   liking: 'Like',
   following: 'Follow',
   unfollowing: 'Unfollow',
   commenting: 'Comentario',
   add_comment: 'Escribe tu comentario aquí. Si no escribes nada, generaremos algo para ti',
   //filters
   filters: 'Filtrar',
   hashtags: 'Tags',
   separated: 'Introduce tags, sepáralos con comas',
   locations: 'Ubicaciones',
   locations_sep: 'Introduce una ubicación',
   search: 'Buscar',
   //exceptions
   blacklist: 'Excepciones',
   hashtag: 'Tags',
   username: 'Nombres de usuario',
   usernames_sep: 'Introduce nombres de usuario, sepáralos con comas',
   keyword: 'Palabras clave',
   keyword_sep: 'Introduce palabras clave, sepáralas con comas',
   //time
   famous: 'Fama',
   faster: 'Pon tu cuenta de Instagram en el Salón de la Fama para incrementar tus seguidores más rápido',
   buy_fame: 'Comprar Fama',
   buy_time: 'Comprar Tiempo',
   timepack: 'Paquetes de Tiempo',
   //onboarding
   add_time: 'Tendrás que añadir tiempo a tu cuenta para incrementar tu actividad. Por ahora no te preocupes, te daremos una prueba gratuita',
   grow: 'Incrementa tu actividad',
   grow_exp: 'Empieza a usar tu tiempo para dar likes, seguir y comentar para incrementar tus seguidores.',
   target: 'Dirígete a tu audiencia',
   target_exp: 'Encuentra a tu audiencia utilizando los tipos de filtración que te damos',
   become: 'Hazte Famoso',
   become_exp: 'Sube a lo alto del salón de la fama y consigue nuevos seguidores mucho más rápido',
   next: 'Siguiente',
   back: 'Atrás',
   ok: 'OK',
   //login again
   update: 'Actualiza tu contraseña',
   verify: 'Verifica tu cuenta',
   restart: 'Reiniciar',
   //hints
   need: 'Necesitas seguir primero',
   need_exp: 'Necesitas activar esto para dejar de seguir a tus nuevos seguidores',
   //hints section
   hall_hint: 'Salón de la Fama',
   hall_hexp: 'Aquí puedes seguir las cuentas que encuentres interesantes. Cada vez que sigas a alguien te agregaremos 5 minutos a tu tiempo restante. ¡Comienza a seguir estas grandiosas cuentas para obtener tiempo gratis! Recuerda que tú puedes ser famoso también. Ve a "Agregar Tiempo" para encontrar más información',
   like_hint: 'Like',
   like_hexp: 'Todo el mundo ama obtener un like en alguna foto. ¡Pruébalo! Darás alrededor de 1000 likes/día',
   follow_hint: 'Follow',
   follow_hexp: 'Seguir a otras cuentas es la forma más eficiente de crecer tu cuenta. Cuando sigues a otras personas tienes una alta probabilidad de que estas te sigan de vuelta.  Darás aproximadamente 300 follows/día',
   unfollow_hint: 'Unfollow',
   unfollow_hexp: 'Comienza por seguir a otros usuarios, cuando estos te siguen de vuelta los dejaremos de seguir y ¡mantendrás los seguidores! Sólo se dejan de seguir a los usuarios seguidos por OWA',
   comment_hint: 'Comentarios',
   comment_hexp: 'Se pueden utilizar para impulsar tus ventas y el tráfico, pueded establecer comentarios para ofrecer descuentos o para promover algo. CUIDADO: Debes cambiar este comentario todos los días, si no Instagram podría suspender tu cuenta',
   hashtags_hint: 'Tags',
   hashtags_hexp: 'Puedes optar por interactuar únicamente con hashtags específicos con el fin de atraer a un público deseado. No introduzcas nada si quieres usar los hashtags más populares',
   locations_hint: 'Ubicación',
   locations_hexp: 'Puedes optar por interactuar únicamente con ubicaciones específicas con el fin de atraer a un público deseado. Ten en cuenta que la especificación de una ubicación poco popular puede disminuir la eficiencia',
   hashtag_hint: 'Lista Negra de Hashtags',
   hashtag_hexp: 'Enlista las etiquetas con las que no deseas interactuar por ningún medio',
   username_hint: 'Lista Negra de Usuarios',
   username_hexp: 'Enlista usuarios con los que no deseas interactuar por ningún medio',
   keyword_hint: 'Lista Negra de Palabras Clave',
   keyword_hexp: 'Este es el tipo de excepción más selectiva. Esto prohibirá cualquier hashtag que contenga la palabra clave especificada. Sé específico con las palabras clave para no prohibir todo el contenido'
 },
 en:{
   // footer
   about: 'About',
   contact: 'Contact',
   usage: 'Terms',
   privacy: 'Privacy Policy',
   logout: 'Sign out',
   // header
   login: 'Sign In',
   time: 'Add Time',
   //landing
   sign: 'Sign in with Instagram',
   mainheader: 'Real followers in no time',
   subheader: 'Just sign in, customize your experience and you will begin to get real followers, ready to interact with you',
   ease: 'Easy to use',
   everyone: 'For everyone',
   organic: 'Completely Organic',
   ease_exp: 'Do not waste time with tons of difficult settings. Starting takes only a couple of clicks, without downloading a thing',
   everyone_exp: 'For content creators, entrepreneurs, musicians, just anyone. The thing is you want to grow',
   organic_exp: 'We guarantee you will interact with real people. No bots or fake accounts',
   header: 'The most powerful and easy to use platform to grow your Instagram account',
   reach: 'Grow your account',
   reach_exp: 'Many people out there are literally buying followers, however these are only fake users that do not interact with those accounts in any meaningful sort of way. OWA Influencers will get you real Instagram likes and followers that are genuinely in love with your profile and your content.',
   reach_exp2: 'Let us manage your account. You only need to set things up and we will take care of the rest, even when you are not online.',
   audience: 'Reach your audience',
   audience_exp: 'There is no point in increase your followers if they unfollow you the next day. In order to engage, you need to reach people that will like your content',
   content: 'Content',
   content_exp: 'With the use of hashtags, target people who have certain interests',
   location: 'Location',
   location_exp: 'Target and interact with users based on locations. We can target local businesses, specific areas, cities and even entire states. Locate your audience',
   exceptions: 'Exceptions',
   exceptions_exp: 'Rule out unwanted hashtags, users and even keywords. Interact only with accounts that are relevant to you',
   users: 'Special Follow',
   users_exp: 'Target the followers or the followings of specefic usernames. Contact us with the usernames you wish to target, and we will take care of all the rest',
   attention: 'Become the center of attention',
   expose: 'Let people see you and follow you',
   hall: 'Hall of Fame',
   hall_exp: 'Make your account the center of attention for other OWA users.',
   hall_exp2: 'This way you will get real followers more quickly and directly',
   package_time: 'Only acquire the time you need',
   time_exp: 'OWA Influencers is with no doubt the best platform to really grow your Instagram account at an affordable cost.',
   time_exp2: 'Here are some of the time packages we have for you',
   day: 'day',
   day_s: 'days',
   per_day: 'per day',
   packages: 'All our packages grows your account and gets you interaction from real users',
   wave: 'Are you ready to get a tons of followers?',
   enter: 'Sign in now and start growing your Instagram account',
   //signin
   signin: 'Sign In',
   ig_user: 'Instagram username',
   ig_password: 'Instagram password',
   verify_account: 'You need to verify your account. Please sign into ',
   ig: 'Instagram',
   verify_account2: ' and verify it was you',
   continue: 'Verified, Continue',
   accept: 'By signing in, you agree to our terms of service',
   //time card
   remaining: 'Remaining Time',
   days: 'Days',
   //hall of fame
   fame: 'Hall of Fame',
   following_hall: 'Following',
   follow: 'Follow',
   // switches
   liking: 'Like',
   following: 'Follow',
   unfollowing: 'Unfollow',
   commenting: 'Comment',
   add_comment: 'Write your comment here. If nothing is used, we will generate some text for you',
   //filters
   filters: 'Filter',
   hashtags: 'Tags',
   separated: 'Enter tags, separate them with commas',
   locations: 'Locations',
   locations_sep: 'Enter a location to search',
   search: 'Search',
   //exceptions
   blacklist: 'Exceptions',
   hashtag: 'Tags',
   username: 'Usernames',
   usernames_sep: 'Enter usernames, separate them with commas',
   keyword: 'Keywords',
   keyword_sep: 'Enter keywords, separate them with commas',
   //time
   famous: 'Fame',
   faster: 'Put your Instagram account in the Hall of Fame to increase your followers faster',
   buy_fame: 'Buy fame',
   buy_time: 'Buy time',
   timepack: 'Time Packages',
   //onboarding
   add_time: 'You will nedd to add time to your account in order to grow your activity. Do not worry right now, we will give you a free trial',
   grow: 'Grow Your Activity',
   grow_exp: 'Start using your time to like, follow, and comment to increase your followers',
   target: 'Target Your Audience',
   target_exp: 'Reach your audience using all the different types of targeting',
   become: 'Become Famous',
   become_exp: 'Scale to the top of the Hall of Fame and start getting new followers much faster',
   next: 'Next',
   back: 'Back',
   ok: 'OK',
   //login again
   update: 'Update your password',
   verify: 'Verify your account',
   restart: 'Restart',
   //hints
   need: 'Need to follow first',
   need_exp: 'You need to activate this in order to unfollow the new followings',
   //hints section
   hall_hint: 'Hall Of Fame',
   hall_hexp: 'Here you can follow accounts you find interesting. Everytime you follow someone we will add 5 minutes to your remaining time. Start following these great accounts to obtain free time! Remember you can be famous too, "Add Time" to find more about it',
   like_hint: 'Like',
   like_hexp: 'Everyone loves a like on their photo. Try it out! You will give about 1000 likes/day',
   follow_hint: 'Follow',
   follow_hexp: 'Following is a very strong form of Instagram growth, when you follow people they have a very high chance of following back. You will give about 300 follows/day',
   unfollow_hint: 'Unfollow',
   unfollow_hexp: 'Begin by following up accounts, when they follow you back we unfollow them afterwards and you keep the followers! You only unfollow users followed by OWA',
   comment_hint: 'Comment',
   comment_hexp: 'This can be used drive up sales & traffic, you may set your comments to offer discounts or to promote something. BEWARE: You should change this comment daily, if not Instagram could ban you',
   hashtags_hint: 'Tags',
   hashtags_hexp: 'You can choose to interact only with specific hashtags in order to attract a specific audience. Leave empty if you want to use most popular hashtags',
   locations_hint: 'Location',
   locations_hexp: 'You can choose to interact only with specific locations in order to attract a specific audience. Keep in mind though that specifying a unpopular location may decrease the efficiency',
   hashtag_hint: 'Hashtags Blacklist',
   hashtag_hexp: 'List the tags you do not want to interact by any means',
   username_hint: 'Username Blacklist',
   username_hexp: 'List usernames you do not want to interact by any means',
   keyword_hint: 'Keyword Blacklist',
   keyword_hexp: 'This is strongest type of exception. This will ban any hashtag containing the specified keyword. Be specific with the keywords so you do not ban all the content'
 }
})

export default Localization
